### ISSUE TITLE
cell_range 

### ISSUE THREAD

**Issue by RoelofSol** [Uriopass/flat_spatial#6]
As an alternative to XYRange consider 

```
pub fn cell_range((x1, y1): CellIdx, (x2, y2): CellIdx) -> impl Iterator<Item = CellIdx> {
    (y1..y2+1).flat_map(move |y| (x1..x2+1).zip(std::iter::repeat(y)))
}
```

**Comment by Uriopass** [comment]
Thanks for the suggestion! Are you using `flat_spatial`? I might do a round of optimizations if I knew people used it :D.  
Your suggestion looks good, although performance in debug mode might suffer. Apart from making the code simpler what is the win?  

Also now that I have a bit more experience I think
`(x1..x2+1).zip(std::iter::repeat(y))`
can be written
`(x1..x2+1).map(move |x| (x, y))`

**Comment by RoelofSol** [comment]
> Are you using flat_spatial?

No not really. I took some inspiration from your approach but i wanted to avoid the extra level of indirection in the end.

**Comment by Uriopass** [comment]
What's your use case? What indirection?  
I'm really focused on performance so I wonder where do you think I could win some.  
If you're talking about the objects, I'm pretty sure setting them to the unit type `()` should optimize it out entirely.

**Comment by RoelofSol** [comment]
I'm just playing around with a bird flocking algorithm in a ecs system (bevy) . 
I don't need the GridCell redirection at the moment. I'm just rebuilding the entire grid every tick. 

If you're looking for performance https://developer.nvidia.com/blog/thinking-parallel-part-iii-tree-construction-gpu/ might have some good ideas.

**Comment by Uriopass** [comment]
Thanks! Indeed if you're reconstructing it's not worth it. My structures are made to be cheaply updated.
